---
version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user
    ports:
      - "7778:5432"
    volumes:
      - db:/var/lib/postgresql/data
  fakesmtp:
    image: gessnerfl/fake-smtp-server:1.10.4
    restart: unless-stopped
    environment:
      - FAKESMTP_PORT=5025
      - FAKESMTP_FORWARDEMAILS=false
      - FAKESMTP_AUTHENTICATION_USERNAME=username
      - FAKESMTP_AUTHENTICATION_PASSWORD=password
      - SERVER_PORT=5080
    ports:
      - 5027:5025
      - 5089:5080
volumes:
  db:

